#!/bin/bash

PACKAGE_MANAGERS=(dpkg xbps unknown)

set -e

main(){
    etckeeper_commit "pre packages list"

    read t < <(tempfilename)

    for pm in "${PACKAGE_MANAGERS[@]}"
    do
	check_"$pm" || continue
        read fp < <(path_"$pm")
        list_"$pm" > "$t"
        cp "$t" "$fp"
        etckeeper_commit "$pm - packages list updated"
    done
    rm "$t"
}

tempfilename(){
    local f
    while true
    do
        f="/tmp/file-$RANDOM-$RANDOM-$RANDOM-$RANDOM"
	if ! [[ -e "$f" ]]
	then
	    echo "$f"
	    break
	fi
    done
}

etckeeper_commit(){
    local msg
    msg="$1"
    if type -p etckeeper > /dev/null
    then
        etckeeper commit -m "$msg" || true
    fi
}

check_dpkg(){
    [[ -e /var/lib/dpkg/status ]]
}

list_dpkg(){
    dpkg --get-selections	
}

path_dpkg(){
    [[ -d '/etc/dpkg' ]] || mkdir '/etc/dpkg'
    echo "/etc/dpkg/packages.txt"
}

check_xbps(){
    [[ -e /var/db/xbps ]]
}

list_xbps(){
    xbps-query -l
}

path_xbps(){
    echo "/etc/xbps-packages.txt"
}

check_unknown(){
    true
}

list_unknown(){
    local c
    {
        for p in /bin /sbin /usr/bin /usr/sbin
        do
	    cd "$p"
	    ls --time-style=long-iso -lid *
	done
    } | sort -n | uniq
}

path_unknown(){
    echo "/etc/bins.txt"
}

main

